- Atk-1.0.gir
- GIRepository-2.0.gir
- GLib-2.0.gir
- GModule-2.0.gir
- GObject-2.0.gir
- Gdk-3.0.gir
- GdkPixbuf-2.0.gir
- GdkX11-3.0.gir
- Pango-1.0.gir
- PangoCairo-1.0.gir
- PangoFT2-1.0.gir
- PangoXft-1.0.gir
Part of #1
Changes seems normal, but effect on current code and docs need be checked
> Gtk v3.22 from Ubuntu Zesty

- PangoCairo-1.0.gir
- dl.sh
- fix.py
- freetype2-2.0.gir
> Fix invalid gir content

- PangoCairo-1.0.gir
- cairo-1.0.gir
- fix.py
> Another fix

- Atk-1.0.gir
- GIRepository-2.0.gir
- GLib-2.0.gir
- GObject-2.0.gir
- Gdk-3.0.gir
- Secret-1.gir
- Soup-2.4.gir
- Vte-2.91.gir
- WebKit2-4.0.gir
- WebKit2WebExtension-4.0.gir
Since our last update there have been improvements in g-ir-scanner, which now
does a better job at preserving const specifiers. Upstream gir files are
already regenerated accordingly. It would be nice to have those in Rust
bindings as well. (Note that we are still using the same Ubuntu release for gir
files).
> Update gir files to get latest improvements in g-ir-scanner.

- fix.sh
As an answer to https://github.com/gtk-rs/gir-files/pull/20#issuecomment-385186632.
> Remove patches for things fixed upstream.

- Gdk-3.0.gir
- fix.sh
See details in https://github.com/gtk-rs/gdk/pull/246
> GDK: GdkFrameClock: fix transfer ownership for timings getters

- fix.sh
Part of https://github.com/gtk-rs/gtk/issues/439
cc @GuillaumeGomez, @sdroege
> Fix GtkIconSize usage

- fix.sh
Part of https://github.com/gtk-rs/gtk/issues/724.
cc @EPashkin @sdroege
> Replace gint with ResponseType when needed

- JavaScriptCore-4.0.gir
- fix.sh
Part of https://github.com/gtk-rs/gtk/issues/884
> Fix gtk shortcut label new

- fix.sh
Part of https://github.com/gtk-rs/gtk/pull/953
Upstream issue: https://gitlab.gnome.org/GNOME/gtk/issues/2418.
I have not changed `transfer-ownership` as I'm waiting for upstream comment to be sure that it needed.
cc @GuillaumeGomez, @sdroege
> Fix function returning glib::Value

- fix.sh
> Add fix.sh entry for GtkEntry::icon-press/-release

- Atk-1.0.gir
- GIRepository-2.0.gir
- GLib-2.0.gir
- GModule-2.0.gir
- GObject-2.0.gir
- Gdk-3.0.gir
- Gdk-4.0.gir
- GdkX11-4.0.gir
- Gsk-4.0.gir
- HarfBuzz-0.0.gir
- JavaScriptCore-4.0.gir
- Pango-1.0.gir
- PangoCairo-1.0.gir
- PangoFT2-1.0.gir
- PangoFc-1.0.gir
- PangoOT-1.0.gir
- PangoXft-1.0.gir
- Secret-1.gir
- Soup-2.4.gir
- Vte-2.91.gir
- WebKit2-4.0.gir
- WebKit2WebExtension-4.0.gir
- dl.sh
- fix.sh
Updates all files with the latest versions from Ubuntu
Groovy.
Supersedes https://github.com/gtk-rs/gir-files/pull/56
> Update to Ubuntu Groovy files and redownload

- GdkWayland-4.0.gir
- fix.sh
otherwise we can't map those types to the ones in wayland-rs-sys
Needed for https://github.com/gtk-rs/gtk4-rs/pull/46
cc @sdroege @GuillaumeGomez
> gdk4 wayland fixes

- Gdk-4.0.gir
- GdkWayland-4.0.gir
- GdkX11-4.0.gir
- Gsk-4.0.gir
- fix.sh
Needed for https://github.com/gtk-rs/gtk4-rs/pull/108
> gtk4: update to 3.99.5

- Gdk-4.0.gir
i mistakenly updated them to an older version :/
> update gtk4/gdk4 from 3.99.5

- Gdk-4.0.gir
- GdkWayland-4.0.gir
- GdkX11-4.0.gir
- Gsk-4.0.gir
> gtk4: re-update

- Gdk-4.0.gir
- GdkWayland-4.0.gir
- Gsk-4.0.gir
- fix.sh
I'm mostly interested in the re-new activate signal in `GtkCheckButton`
> gtk4: update to 4.1.2

- fix.sh
Linked to https://github.com/gtk-rs/gtk3-rs/issues/89.
I'll send the PR to gtk3-rs once this one is merged.
> Fix invalid Image and StackSwitcher icon-size property type

- Gdk-4.0.gir
- Gsk-4.0.gir
> bump GTK 4 gir files to 4.4

- Pango-1.0.gir
- fix.sh
> pango: add a workaround for the broken GlyphVisAttr

- Gdk-4.0.gir
- Gsk-4.0.gir
Contains fixes for https://github.com/gtk-rs/gtk4-rs/issues/707
> update to a newer gtk4 gir files

- .github/workflows/CI.yml
- .gitignore
This PR updates the 'CI' workflow (`CI.yml`) to point to the correct `gtk-sys` and `gtk4-sys` crates and Gir TOMLs.
> 'CI' workflow: gtk-rs/sys has been archived

- Atk-1.0.gir
- GLib-2.0.gir
- GObject-2.0.gir
- Gdk-3.0.gir
- Gdk-4.0.gir
- GdkPixbuf-2.0.gir
- GdkX11-3.0.gir
- GdkX11-4.0.gir
- Graphene-1.0.gir
- HarfBuzz-0.0.gir
- Pango-1.0.gir
- PangoFc-1.0.gir
- fix.sh
The pango one contains a bunch of missing since annotations, will mark them as a review here until they are handled upstream
> update gtk4 / pango gir files

- Atk-1.0.gir
- Gdk-3.0.gir
- Gdk-4.0.gir
Glib girs are held back until upstream issue is resolved.
https://github.com/gtk-rs/gir-files/pull/114#discussion_r876844419
> Update gir files

- .github/workflows/regenerate_scheduled.yml
- GdkWin32-4.0.gir
- dl-win32.sh
- fix.sh
- win32-1.0.gir
Generated from MSYS2 environment, with:
https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/4965
> Add GdkWin32-4.0.gir

- Gdk-4.0.gir
- Gsk-4.0.gir
To include property annotations fixes that haven't landed upstream yet
> Manually update gtk4 gir files
